name: "Autopopulate your contribution graph"
author: "duckduckquaquackk <r4sttyxgl5091v@duck.com>"
description: "This action will automatically push empty commits to one of your GitHub repos."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "grid"
  color: "green"
