on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [master]

jobs:
  single-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: amackzie@gmail.com
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: amackzie@gmail.com
          MAX_DAYS: 365
          MIN_COMMITS_PER_DAY: 0
          MAX_COMMITS_PER_DAY: 5
          GIT_HOST: "github.com"
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_COMMIT_MESSAGE: "chore: update contribution graph"
          INCLUDE_WEEKENDS: "true"
          FORCE_PUSH: "false"
